### ISSUE TITLE
Add an indicator that cron is running in the cron details screen

### ISSUE THREAD

**Issue by mvintila** [opsicl/saltpeter-ui#29]
Right now, until some minions actually respond and start there is no indication that a cron is running. There should be a way to tell, as the information is already present, and a cron turns blue correctly in the main sreen immediately when it starts running.

As a suggestion - a blue play arrow can be displayed in the same place as the red exclamation mark is displayed on cron overlap.

Same can be done for all crons states, not run, failed, succesful, etc.

**Comment by radumariusrobert14** [comment]
fixed in next release(v3.0.0)

**Comment by radumariusrobert14** [comment]
fixed in v2.1.0
